server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - JwtAuthFilter
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_BASE_URL:http://localhost:8081}
          predicates:
            - Path=/auth/**
        - id: classroom-service
          uri: ${CLASSROOM_SERVICE_BASE_URL:http://localhost:8082}
          predicates:
            - Path=/grades/**, /classrooms/**
        - id: course-service
          uri: ${COURSE_SERVICE_BASE_URL:http://localhost:8083}
          predicates:
            - Path=/courses/**
        - id: user-service
          uri: ${TEACHER_SERVICE_BASE_URL:http://localhost:8084}
          predicates:
            - Path=/teachers/**
        - id: schedule-service
          uri: ${SCHEDULE_SERVICE_BASE_URL:http://localhost:8085}
          predicates:
            - Path=/schedule/**
        - id: student-service
          uri: ${STUDENT_SERVICE_BASE_URL:http://localhost:8086}
          predicates:
            - Path=/students/**
        - id: maintenance-service
          uri: ${MAINTENANCE_SERVICE_BASE_URL:http://localhost:8087}
          predicates:
            - Path=/facilities/**, /equipments/**
        - id: attendance-service
          uri: ${ATTENDANCE_SERVICE_BASE_URL:http://localhost:8088}
          predicates:
            - Path=/attendance/**
        - id: gradebook-service
          uri: ${GRADEBOOK_SERVICE_BASE_URL:http://localhost:8089}
          predicates:
            - Path=/gradebook/entries/**
        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_BASE_URL:http://localhost:8090}
          predicates:
              - Path=/teacher/notifications/**
      globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "https://front-end-funda.vercel.app"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders: "*"

  main:
    web-application-type=reactive: